name: Test
on:
  - push
  - pull_request
jobs:
  test:
    strategy:
      matrix:
        python:
          - '3.12'
          - '3.13'
        platform:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
      - name: Install test dependencies
        run: |
          pip install --upgrade build check-manifest twine black pytest pytest-cov
          pip install .
      - name: Lint
        run: black . --check
      - name: Build
        run: |
          check-manifest
          python -m build
          python -m twine check dist/*
      - name: Test and report coverage
        run: pytest --cov --cov-branch --cov-report=xml
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: Run CLOC
        run: cloc --exclude-dir=dist,venv,build,tests --json . | jq '"CLOC="+(.Python.code|tostring)' -r  >> $GITHUB_ENV
      - name: Create CLOC badge
        uses: schneegans/dynamic-badges-action@v1.7.0
        with:
          auth: ${{ secrets.CLOC_GIST_SECRET }}
          gistID: 5d8f9b1d4b414b7076cf84f4eae089d9
          filename: cloc.json
          label: Lines of Python
          message: ${{ env.CLOC }}
          color: orange
